### ISSUE TITLE
Create an evaluation script

### ISSUE THREAD

**Issue by ptakopysk** [ufal/ST2020#1]
- randomly set some features in dev to "?"
- compare predicted values to real values

**Comment by vastlik** [comment]
I have created an evaluation script, which expects three files, first is input file with "?" in it, so the script knows which values were predicted. The second one is the whole CSV with filled values, and the third one is the CSV with golden values.
The second approach would be just to expect only the filled values and the golden values, which would save one file, however, I thought that using the previous evaluation method was more convenient. 
However, I am open to change this approach if you find it unsuitable.
